### ISSUE TITLE
compile error on ash update

### ISSUE THREAD

**Issue by matt-beanland** [diffo-dev/diffo#48]
Compile error on Ash update to 3.10.0, see also https://github.com/diffo-dev/diffo_example/issues/5

```elixir
== Compilation error in file lib/diffo/provider/components/entity.ex ==
** (ArgumentError) cannot escape #Reference<0.3179060992.1415708675.199533>. The supported values are: lists, tuples, maps, atoms, numbers, bitstrings, PIDs and remote functions in the format &Mod.fun/arity
    (elixir 1.18.4) src/elixir_quote.erl:554: :elixir_quote.argument_error/1
    (elixir 1.18.4) src/elixir_quote.erl:462: :elixir_quote.do_quote_simple_list/3
    (elixir 1.18.4) src/elixir_quote.erl:462: :elixir_quote.do_quote_simple_list/3
    (elixir 1.18.4) src/elixir_quote.erl:150: :elixir_quote.do_escape/2
    (elixir 1.18.4) src/elixir_quote.erl:170: :elixir_quote."-do_escape/2-lc$^1/1-0-"/3
    (elixir 1.18.4) src/elixir_quote.erl:171: :elixir_quote."-do_escape/2-lc$^1/1-0-"/3
    (spark 2.3.14) /Users/beanlanda/git/diffo/lib/diffo/provider/components/entity.ex:5: Spark.Dsl.__before_compile__/1
```

**Comment by matt-beanland** [comment]
ash 3.10.0 uses erlang 28.1 and elixir 1.19.0-otp-28 but passes its tests on 1.18.4-otp-28 so don't know what is going on.

**Comment by matt-beanland** [comment]
diffo works with elixir 1.19.4-otp-28 but not 1.18.4-otp-28, suspect ash is missing some tests.
